import type { Metadata } from "next";
import { Lato, Playfair_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/src/components/navbar";
import Footer from "../components/footer";

const playFair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playFair.variable} ${lato.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col font-lato bg-[#E2D9C8]">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
